### PR TITLE
soap plugin fixes

### PR DESCRIPTION
**Pull request by tenzap**
See commit messages

### CODE REVIEW

**Comment by tenzap** [comment]
Please don't squash when merging. Leave the individual commits as is. Thanks

**Comment by kingster** [comment]
Probably upgrade the library using composer?

**Comment by tenzap** [comment]
> Probably upgrade the library using composer?

as you like

**Comment by tenzap** [comment]
Please merge #24 before this one

**Comment by tenzap** [comment]
Conflicts are fixed now.

**Comment by tenzap** [comment]
Can you merge please? You may move to composer later on.

BTW, every time you merge a PR, after that all other PRs show: "This branch is out-of-date with the base branch" and I have to click update branch. Is this normal?

**Pull request merged**
