### PR TITLE
sms_to_wordpress: upgrade IXR Library

### PR DESCRIPTION
**Pull request by tenzap**
The older version used $HTTP_RAW_POST_DATA
Upgrading to a newer version that has been updated to support newer versions
of PHP.

### CODE REVIEW

**Comment by kingster** [comment]
Should we instead move to composer/similar for dependency management so that we copy-paste external libraries in our repo?

**Comment by tenzap** [comment]
I don't know. I don't know composer and how it could integrate with kalkun/ci3. If you think it's better maybe you could give it a try? I was a bit lost in trying to include the headers and in the management of the namespaces. I devel as a hobby so I don't have strong knowledge on these items.

**Comment by tenzap** [comment]
Sometimes I also wonder whether some of these plugins are still relevant nowadays. Some are really concerning, security-wise.

**Comment by kingster** [comment]
> I don't know. I don't know composer and how it could integrate with kalkun/ci3. If you think it's better maybe you could give it a try? I was a bit lost in trying to include the headers and in the management of the namespaces. I devel as a hobby so I don't have strong knowledge on these items.

No problem, I will go ahead and merge this PR. I will take a stab at using composer in a separate PR. At that time maybe we can tackle removing these plugin codes.

> Sometimes I also wonder whether some of these plugins are still relevant nowadays. Some are really concerning, security-wise.

Very true. A lot of the ecosystem has evolved in the past 8 years. maybe we mark vulnerable plugins with appropriate tags and then later remove them in later versions.

**Comment by kingster** [comment]
Attempted using composer #19 Please have a look

**Pull request closed without merging**
